sudo: true
notifications:
  email: false
language: node_js
node_js:
  - "7"
before_install:
  - export CC=`which clang`
  - export CXX=`which clang++`
  - sudo ln -s `which node` /usr/bin/node
  - sudo ln -s `which npm` /usr/bin/npm
install: ./install-dependencies.sh
script: sudo -E scons install